# Generated by Django 3.1.7 on 2021-04-17 17:54

from django.conf import settings
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=32)),
                ('cleanData', jsonfield.fields.JSONField(default=dict)),
                ('unCleanData', jsonfield.fields.JSONField(default=dict)),
                ('haveRead', models.ManyToManyField(related_name='haveRead', to=settings.AUTH_USER_MODEL)),
                ('isFavourite', models.ManyToManyField(related_name='isFavourite', to=settings.AUTH_USER_MODEL)),
                ('readingNow', models.ManyToManyField(related_name='readingNow', to=settings.AUTH_USER_MODEL)),
                ('toRead', models.ManyToManyField(related_name='toRead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
