# Generated by Django 3.1.7 on 2021-05-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='createTime',
            new_name='createdTime',
        ),
        migrations.RenameField(
            model_name='bookreview',
            old_name='ratingValue',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='reply',
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookReviews', to='book.book'),
        ),
    ]
