# Generated by Django 2.2.9 on 2020-05-16 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=1024)),
                ('authors', models.CharField(max_length=1024)),
                ('publisher', models.CharField(max_length=1024)),
                ('published_date', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=8192)),
                ('isbn_13', models.CharField(max_length=32)),
                ('isbn_10', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=1024)),
                ('average_rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=1024)),
                ('favourites', models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('haveread', models.ManyToManyField(related_name='haveread', to=settings.AUTH_USER_MODEL)),
                ('readingnow', models.ManyToManyField(related_name='readingnow', to=settings.AUTH_USER_MODEL)),
                ('toread', models.ManyToManyField(related_name='toread', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
